dist: trusty
cache:
  - /tmp/texlive
  - $HOME/.texlive
install:
  - source tex/travis.sh
  - wget https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_amd64.deb
  - sudo dpkg -i hugo*.deb
before_script:
  - latex --version
  - latexmk --version
  - hugo version
script: make
