dist: trusty
sudo: false
language: python
addons:
  apt:
    packages:
      - gimp
install:
  # Install Python packages
  - pip install -r requirements.txt
  # Install TeX Live
  - wget --directory-prefix /tmp
      http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xzv -C /tmp -f /tmp/install-tl-unx.tar.gz
  - /tmp/install-tl-*/install-tl --profile=./etc/texlive.profile
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  # Install packages
  - tlmgr install
      amscls
      amsmath
      beamer
      booktabs
      caption
      chngcntr
      cm-super
      collection-fontsrecommended
      enumitem
      environ
      etoolbox
      fourier
      geometry
      graphics
      hyperref
      l3kernel
      l3packages
      latex-bin
      latexmk
      lipsum
      mathtools
      mdframed
      microtype
      ms
      nag
      needspace
      oberdiek
      pgf
      pgfplots
      tikz-3dplot
      tocloft
      tools
      translator
      trimspaces
      url
      xcolor
  # Install Hugo
  - wget https://github.com/spf13/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.tar.gz
      -O /tmp/hugo.tar.gz
  - mkdir /tmp/hugo
  - tar xzv -C /tmp/hugo -f /tmp/hugo.tar.gz
  - export PATH=$PATH:/tmp/hugo
before_script:
  - python --version
  - pip --version
  - scons --version
  - latex --version
  - latexmk --version
  - hugo version
script: scons
deploy:
  provider: script
  skip_cleanup: true
  script: scons deploy
  on:
    branch:
      - master
