dist: trusty
language: go
addons:
  apt:
    packages:
      - xzdec
      - texlive
      - latexmk
install:
  - tlmgr init-usertree
  - tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
  - tlmgr install beamer chngcntr enumitem environ etoolbox lipsum nag pgf xcolor
  - go get -v github.com/spf13/hugo
before_script:
  - latex --version
  - latexmk --version
  - hugo version
script: make
