dist: xenial
sudo: false
language: ruby
addons:
  apt:
    packages:
      - gimp
cache:
  directories:
    - $HOME/.cache/Tectonic
install:
  # Thanks to <https://malramsay.com/post/compiling_latex_on_travis/>
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda install -y -c conda-forge tectonic==0.1.11
script:
  - make
deploy:
  provider: script
  skip_cleanup: true
  script: make deploy
  on:
    branch:
      - master
