# Site settings
title: Intuitive Explanations
email: radon.neon@gmail.com
description: Understand, don't memorize.
url: "https://www.intuitiveexplanations.com"
github_username: raxod502

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-redirect-from
exclude:
  - _vendor
  - _src
  - Gemfile
  - Gemfile.lock

# Theme configuration
header_pages:
  - title: Projects
    url: /about/projects/
  - title: Math
    url: /math/
  - title: Resume
    url: /assets/Resume.pdf
  - title: About
    url: /about/site/
minima:
  social_links:
    github: raxod502
google_analytics: UA-111346837-2

# Page configuration
defaults:
  - scope:
      path: ""
    values:
      layout: page
