# Site settings
title: Intuitive Explanations
email: your-email@example.com
description: Understand, don't memorize.
url: "https://www.intuitiveexplanations.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: raxod502

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Page configuration
defaults:
  - scope:
      path: ""
    values:
      layout: page
