name: Build and deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
      - name: Checkout submodules
        env:
          FICTION_WRITING: ${{ secrets.CLONE_URL_FICTION_WRITING }}
          RESUME: ${{ secrets.CLONE_URL_RESUME }}
        run: |
          git config -f .gitmodules submodule.doc/resume.url "${RESUME}"
          git config -f .gitmodules submodule.doc/stories.url "${FICTION_WRITING}"
          git submodule update --init --recursive
      - name: Build and deploy
        env:
          NETLIFY_KEY: ${{ secrets.NETLIFY_KEY }}
        run: |
          make docker CMD="make checklinks all deploy JEKYLL_ENV=production"
